name: wpay_app
description: A new Flutter project.


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: ^1.1.0

  event_bus: ^1.1.0

  decimal: ^0.3.0
  flutter_html: ^0.9.8
  # http package https://pub.dartlang.org/packages/http#-readme-tab-
  http: ^0.12.0+2

  #极光推送
  jpush_flutter:
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master

  #  jmessage_flutter:
  #    git:
  #      url: git://github.com/jpush/jmessage-flutter-plugin.git
  #      ref: master

  cached_network_image: ^2.0.0-rc

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #------------------------
  # Added by tt
  # swiper
  flutter_swiper: ^1.1.4

  # State management
  scoped_model: ^1.0.1

  # Auto size for text
  auto_size_text: ^1.1.0

  # chart library
  fcharts: ^0.0.10

  # Add features to the Android / iOS keyboard
  keyboard_actions: ^1.0.3

  # persistent store for simple data
  shared_preferences: ^0.5.6+2

  # Flutter plugin for selecting images from the Android and iOS image library,
  # and taking new pictures with the camera.
  image_picker: ^0.6.0+16

  # A collection of loading indicators animated.
  flutter_spinkit: ^3.1.0

  # image compress
  flutter_image_compress: ^0.6.3
  #------------------------

  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter.
  qr_flutter: ^2.0.0+51
  #------------------------
  flutter_webview_plugin: ^0.3.5

  flutter_slidable: "^0.4.9"

  fluttertoast: ^3.1.0

  url_launcher: ^5.0.2

  pull_to_refresh: ^1.4.0


  json_serializable: ^2.2.1
  rxdart: ^0.21.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # images
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  # Added by mobilecheng
  fonts:
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Light.ttf
